spring:
  profiles:
    # 引用配置文件,提供默认配置信息
    include: default
    # 激活环境配置文件,提供环境变量信息
    active: dev
  application:
    name: customer
configcenter:
  app-id: customer
  server-url: http://127.0.0.1:6220
  enable: true
  profile-id: dev

ant:
  env:
    refresh-placeholders:
      enable: true
    refresh-properties:
      enable: true
